<a href="https://colab.research.google.com/github/biobutcoder/Nunnari-Datascience-course-with-ai/blob/main/nunnari1d2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Nunnari Datascience Tasks

Date : 15/04/2026




Lists

In [ ]:
l1 = ["Theeran","Ratchasan","Kaithi","Vikram Vedha","Asuran"]
print("first movie : ",l1[0])
print("last movie : ",l1[len(l1)-1])

first movie :  Theeran
last movie :  Asuran


In [ ]:
l1.append("Dhurandhar")
l1.pop(1)
print(l1)

['Theeran', 'Kaithi', 'Vikram Vedha', 'Asuran', 'Dhurandhar']


In [ ]:
l1.sort()
print(l1)

['Asuran', 'Dhurandhar', 'Kaithi', 'Theeran', 'Vikram Vedha']


In [ ]:
print("length : ",len(l1))
if "Vikram Vedha" in l1:
  print("Vikram Vedha is in the list")
else:
  print("Vikram Vedha is not in the list")

length :  5
Vikram Vedha is in the list


Tuples

In [ ]:
t1 = ("Delhi","Mumbai","Chennai","Kolkata","Bangalore")
print("second city : ",t1[2-1])
print("fourth city : ",t1[4-1])

second city :  Mumbai
fourth city :  Kolkata


In [ ]:
t1[4]="Hyderbad"
print(t1)
# tuple is unchangable

TypeError: 'tuple' object does not support item assignment

In [ ]:
(a,b,c,d,e) = t1
print(a)
print(b)
print(c)
print(d)
print(e)

Delhi
Mumbai
Chennai
Kolkata
Bangalore


In [ ]:
l1=list(t1)
l1.append("Hyderabad")
t2=tuple(l1)
print(t2)

('Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Bangalore', 'Hyderabad')


Dictionary

In [ ]:
d1 = { "name" : "Asvanth","age" : "19","grade" : "O","city" : "Coimbatore"}
print(d1)

{'name': 'Asvanth', 'age': '19', 'grade': 'O', 'city': 'Coimbatore'}


In [ ]:
x=d1.keys()
print("only keys : ",x)
y=d1.values()
print("only values : ",y)
z=d1.items()
print("key-value pairs : ",z)

only keys :  dict_keys(['name', 'age', 'grade', 'city'])
only values :  dict_values(['Asvanth', '19', 'O', 'Coimbatore'])
key-value pairs :  dict_items([('name', 'Asvanth'), ('age', '19'), ('grade', 'O'), ('city', 'Coimbatore')])


In [ ]:
d1["grade"] = "A"
d1["email"] = "abcd@gmail.com"
print(d1)


{'name': 'Asvanth', 'age': '19', 'grade': 'A', 'city': 'Coimbatore', 'email': 'abcd@gmail.com'}


In [ ]:
d1.pop("city")
print(d1)

{'name': 'Asvanth', 'age': '19', 'grade': 'A', 'email': 'abcd@gmail.com'}


Sets

In [ ]:
s1 = {"science","maths","social","computer"}
s2 = {"science","social","english","tamil"}
print(s1)
print(s2)


{'computer', 'science', 'social', 'maths'}
{'tamil', 'science', 'english', 'social'}


In [ ]:
s3=s1.union(s2)
print("union : ",s3)
s4=s1.intersection(s2)
print("intersection : ",s4)
s5=s1.difference(s2)
print("difference : ",s5)

union :  {'science', 'social', 'tamil', 'english', 'computer', 'maths'}
intersection :  {'science', 'social'}
difference :  {'computer', 'maths'}


In [ ]:
s1.add("value science")
s2.remove("tamil")
print(s1)
print(s2)

{'value science', 'science', 'social', 'computer', 'maths'}
{'science', 'english', 'social'}


In [ ]:
if "computer" in s1:
    if "computer" in s2:
        print(" computer is present in both sets")
    else:
        print("computer is not present in both sets")

computer is not present in both sets


Functions

In [ ]:
def greet(name):
    return f"Hello, {name} ! Welcome to Day 2."
print(greet("Asvanth"))


Hello, Asvanth ! Welcome to Day 2.


In [ ]:
def add_numbers(a,b):
    return a+b
print(add_numbers(3,5))

8


In [ ]:
def find_max(a,b,c):
    return max(a,b,c)
print(find_max(1,-70,32))

32


In [ ]:
def is_even(a):
    if a %2 == 0 :
        print("even")
    else:
        print("odd")
is_even(46)
is_even(37)

even
odd




> Default Parameters



In [ ]:
def introduce(name,language="Python"):
    print(f"{name} is learning {language} ")
introduce("Asvanth")

Asvanth is learning Python 


In [ ]:
introduce("Asvanth")
introduce("Asvanth",language="SQL")

Asvanth is learning Python 
Asvanth is learning SQL 


In [ ]:
def calculate_discount(price,discount=10):
    final=price-((price*discount)/100)
    return final
print(calculate_discount(250))

225.0


if/else/elif

In [ ]:
a=int(input("Enter a number : "))
if a==0:
    print("number is zero")
elif a>0:
    print("number is positive")
else:
    print("number is negative")

Enter a number : 6
number is positive


In [ ]:
a=int(input("Enter the score : "))
if a >89:
    print("A Grade")
elif 79<a<90:
    print("B Grade")
elif 69<a<80:
    print("C Grade")
elif 59<a<70:
    print("D Grade")
else:
    print("F Grade")

Enter the score : 60
D Grade


In [ ]:
a=int(input("Enter a year : "))
if a% 400 == 0:
    print("leap year")
elif a%100 == 0:
    print("not a leap year")
elif a%4 == 0:
    print("leap year")
else:
    print("not a leap year")

For loops

In [ ]:
for i in range(1,21):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
for i in range(1,50):
  if i%2 == 0:
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48


In [ ]:
l1 = ["mango","banana","jackfruit","guava","custard apple"]
for i in l1:
  print("fruit name : ",i)
  print("index no : ",l1.index(f"{i}"))

fruit name :  mango
index no :  0
fruit name :  banana
index no :  1
fruit name :  jackfruit
index no :  2
fruit name :  guava
index no :  3
fruit name :  custard apple
index no :  4


In [ ]:
a=0
for i in range(1,101):
  a=a+i
print(a)

5050


In [3]:
st = input("Enter a string : ")
a=0
for i in st:
  if(i=='a'or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
    a=a+1
print(a)

Enter a string : dictionary
4


Numpy

1D Arrays

In [4]:
import numpy as np
ar = np.array([10,20,30,40,50])
print(ar)

[10 20 30 40 50]


In [7]:
print(np.zeros(10,dtype=int))
np.ones(10,dtype=int)

[0 0 0 0 0 0 0 0 0 0]


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [13]:
np.random.randint(1,100,8)

array([82, 90, 33, 28, 95, 35, 99,  6])

2 D array creation

In [14]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
np.full((4,4),7,dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [21]:
np.random.rand(3,4)

array([[0.23823812, 0.13675772, 0.64915227, 0.31996322],
       [0.05652605, 0.32375374, 0.87474596, 0.27046167],
       [0.29502124, 0.84554856, 0.46205147, 0.08917339]])

In [22]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array atributes

In [30]:
print("dimension : ",ar.ndim)
print("shape : ",ar.shape)
print("size : ",ar.size)
print("data type : ",ar.dtype)
print("item size : ",ar.itemsize)
print("bytes consumed : ",ar.nbytes)

dimension :  2
shape :  (3, 3)
size :  9
data type :  int64
item size :  8
bytes consumed :  72


Data types

In [31]:
ar = np.array([9,6,8,6,5,0])
print(ar.dtype)

int64


In [32]:
ar = np.array([2.3,8.1,9.2,7.4,93.0,8.5])
print(ar.dtype)

float64


In [33]:
ar = np.array([11,22,33,44,45,48])
nar = ar.astype(float)
print(nar)

[11. 22. 33. 44. 45. 48.]


In [37]:
ar = np.array([1,2.5,3,4.7,8.9,66])
print(ar.dtype)

float64


In [41]:
ar = np.array([1,2,3,4,5,6],dtype=str)
print(ar)
print(ar.dtype)

['1' '2' '3' '4' '5' '6']
<U1


Special Array creation function

In [42]:
ar=np.zeros(10)
ar[5]=99
print(ar)

[ 0.  0.  0.  0.  0. 99.  0.  0.  0.  0.]


In [44]:
np.arange(0,51,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [47]:
ar = np.eye(5,5,dtype=int)
print(ar)
for i in range(5):
  for j in range(5):
    if i==j:
      print(ar[i,j])

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
1
1
1
1
1


In [48]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])
print(ar1)
print(ar2)
ar3 = np.vstack((ar1,ar2))
print(ar3)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])
print(ar1)
print(ar2)
ar3 = np.hstack((ar1,ar2))
print(ar3)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


Indexing and slicing

In [63]:
ar = np.arange(1,16)
print(ar)
print(ar[0:4])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4]


In [64]:
print(ar[-3:])

[13 14 15]


In [69]:
for i in range(15):
  if i%2==0:
    print(ar[i])

1
3
5
7
9
11
13
15


In [70]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(ar[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [77]:
print("second row : ",ar[1])
print("third column : ",ar[:,2])

second row :  [4 5 6]
third column :  [3 6 9]


Basic Array Operations

In [81]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([6,7,8,9,10])
print(ar1)
print(ar2)
ar3 = np.add(ar1,ar2)
ar4 = np.subtract(ar1,ar2)
ar5 = np.multiply(ar1,ar2)
ar6 = np.divide(ar1,ar2)
print("add : ",ar3)
print("sub : ",ar4)
print("multiply : ",ar5)
print("divide : ",ar6)

[1 2 3 4 5]
[ 6  7  8  9 10]
add :  [ 7  9 11 13 15]
sub :  [-5 -5 -5 -5 -5]
multiply :  [ 6 14 24 36 50]
divide :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [82]:
ar = np.arange(1,11)
print(ar)
print("result : ",np.multiply(ar,3))

[ 1  2  3  4  5  6  7  8  9 10]
result :  [ 3  6  9 12 15 18 21 24 27 30]


In [84]:
ar = np.array([4,9,16,25,36])
print(ar)
rar = np.power(ar,0.5)
print("result : ",rar.astype(int))

[ 4  9 16 25 36]
result :  [2 3 4 5 6]


In [88]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print("min : ",np.min(ar))
print("max : ",np.max(ar))
print("sum : ",np.sum(ar))
print("mean : ",np.mean(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
min :  1
max :  9
sum :  45
mean :  5.0


In [90]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print("sum of 1st row : ",np.sum(ar[0]))
print("sum of 2nd row : ",np.sum(ar[1]))
print("sum of 3rd row : ",np.sum(ar[2]))
print("sum of 1st column : ",np.sum(ar[:,0]))
print("sum of 2nd column : ",np.sum(ar[:,1]))
print("sum of 3rd column : ",np.sum(ar[:,2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of 1st row :  6
sum of 2nd row :  15
sum of 3rd row :  24
sum of 1st column :  12
sum of 2nd column :  15
sum of 3rd column :  18
